# Generated by Django 4.2.7 on 2024-06-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('nombre_estadio', models.CharField(blank=True, max_length=100, null=True)),
                ('edad_promedia_plantilla', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('capacidad_estadio', models.PositiveIntegerField(default=None)),
                ('tamaño_plantilla', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clubId', models.IntegerField(default=None)),
                ('club', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=100)),
                ('posicion_especifica', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pie_bueno', models.CharField(blank=True, max_length=12, null=True)),
                ('valor_mercado_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_mercado_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ultimo_año', models.IntegerField(default=None)),
                ('altura', models.CharField(blank=True, max_length=100, null=True)),
                ('agente', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
            ],
        ),
        migrations.CreateModel(
            name='ValoresDeMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('valor_de_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('club_id', models.IntegerField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_jugador', models.CharField(blank=True, max_length=100, null=True)),
                ('edad_jugador', models.IntegerField(blank=True, null=True)),
                ('posicion_jugador', models.CharField(blank=True, max_length=50, null=True)),
                ('posicion_especifica_jugador', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidad_jugador', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_club', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
