# Generated by Django 4.2.7 on 2024-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_juegousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegousuario',
            name='temporizador_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
