# Generated by Django 4.2.7 on 2024-06-19 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_juegousuario_temporizador_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegousuario',
            name='bloqueado_hasta',
        ),
        migrations.RemoveField(
            model_name='juegousuario',
            name='temporizador_inicio',
        ),
        migrations.AddField(
            model_name='juegousuario',
            name='ultima_partida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
