# Generated by Django 4.2.7 on 2024-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_juegousuario_bloqueado_hasta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegousuario',
            name='ultima_partida',
        ),
        migrations.AddField(
            model_name='juegousuario',
            name='partida_iniciada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
