# Generated by Django 4.2.7 on 2024-06-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_juegousuario_partida_completada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='clubId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
